version: '3.0'
services:
    mysql:
        image: alicek106/composetest:mysql
        command: mysqld
    web:
        image: alicek106/composetest:web
        ports:
            - "80:80"
        links:
            - mysql:db
        command: apache2ctl -D FOREGROUND