version: '3.0'
services:
    myservice:
        image: nginx
        networks:
            - mynetwork
networks:
    app_net:
        ipam:
            driver: mydriver
            configs:
                subnet: 172.20.0.0/16
                ip_range: 172.20.5.0/24
                gateway: 172.20.5.1